### ISSUE TITLE
question

### ISSUE THREAD

**Issue by sec13b** [nickvourd/Responder-Parser#1]
so first configure and after run the responder

like:

1. sudo python3 Responder-Parser.py -c 1122334455667788 --cleardb -m WIN10-TEST.CORP.LOCAL -d corp.local -b --smtp off --smb on
2. sudo python3 Responder.py -I eth0

**Comment by nickvourd** [comment]
Hello mate, exactly, first configure and then execute Responder, to avoid  any issue please use `-b` which keeps back up. If you want to restore the original configuration files of Responder without edits of Responder-Parser just run this:

sudo python3 Responder-Parser.py -r. 

For any other clarifications please let me know :)

**Comment by nickvourd** [comment]
Is it ok, to close the ticket issue?

**Comment by sec13b** [comment]
yes. thank you
